SVY-20811 double check all warnings that are introduced when "Any" types of the argument are not seen as always good
some fixes for the Destructoring. A fix for the exception:
java.lang.UnsupportedOperationException: Destructuring declarations do
not have a single identifier
  at org.eclipse.dltk.javascript.ast.DestructuringVariableDeclaration.getIdentifier(DestructuringVariableDeclaration.java:62)
  at org.eclipse.dltk.javascript.internal.core.codeassist.SelectionVisitor.initializeVariable(SelectionVisitor.java:137)

But also fixes for for gettin the right types when destructoring and
Array or Record type, if the Array is of 1 type we will just take that
one
else we will look at the specific index of the literal array or record
types name to check that type and assign that.